In [33]:
import pandas as pd

pd.set_option('display.max_columns', None)  # Виводити всі колонки
pd.set_option('display.width', 1000)        # Збільшити ширину
pd.set_option('display.max_colwidth', 150)

EOName = 'EOName'
AreaName='AreaName'
TerName = 'TerName'
Subj = 'Subj'

file_path = 'big_files/Odata2024File.csv'

def customFilter(df):
    return df
    #return df[df[AreaName] == 'м.Чернігів']

def load_data_2024(file_path, columns):
    df = pd.read_csv(file_path, usecols=columns)
    return df

def clean_data_2024(df, fileSubj):
    column_mapping = {
        fileSubj: Subj,
    }

    df.rename(columns=column_mapping, inplace=True)
    df[Subj] = df[Subj].astype(str).str.replace(',0$', '', regex=True)
    df[Subj] = pd.to_numeric(df[Subj], errors='coerce')
    filtered_data = df.dropna()
    return customFilter(filtered_data)


def data_2024(file_path, AreaName, TerName, EOName, fileSubj):
    file_data = load_data_2024(file_path, [AreaName, TerName, EOName, fileSubj])
    clean_data = clean_data_2024(file_data, fileSubj)
    return clean_data

def statistics(data_frame, subj):
    mean = data_frame[subj].mean()
    std_dev = data_frame[subj].std()
    normal_high = mean + std_dev
    normal_low = mean - std_dev
    stats = {
        'mean': round(mean, 2),
        'normal_high': round(normal_high, 2),
        'normal_low': round(normal_low, 2),
        'max': round(data_frame[subj].max(), 2),
        'min': round(data_frame[subj].min(), 2),
        'median': data_frame[subj].median(),
        'q_25': data_frame[subj].quantile(0.25),
        'q_75': data_frame[subj].quantile(0.75),
    }
    return stats

In [34]:
def main(df):
    stats = statistics(df, Subj)
    print(pd.DataFrame(list(stats.items()), columns=['Statistic', 'Value']))

    df_top = top(df, EOName, Subj, calculate_points_10)
    print(df_top.head(15))

    #df_limited = df_top.head(200)
    #df_limited.insert(0, 'Rate', range(1, len(df_limited) + 1))

    #markdown_table = df_limited.to_markdown(index=False)
    #print(markdown_table)

    #html_table = df_limited.to_html(index=False)
    #print(html_table)

    #stats = statistics(df_top, 'count')
    #print(pd.DataFrame(list(stats.items()), columns=['Statistic', 'Value']))

def calculate_points_10(row):
    c = .5
    d = 0
    x = row['count']
    return row['normal_low'] * (c + (x+d)/(x+d+1))

def top(df, groupName, subj, calculate_points):
    grouped = df.groupby([groupName]).agg(
        count=(subj, 'size'),
        mean=(subj, 'mean'),
        std_dev= (subj, 'std'),
        max=(subj, 'max'),
        min=(subj, 'min'),
    ).reset_index()
    grouped['normal_high'] = round(grouped['mean'] + grouped['std_dev'], 1)
    grouped['normal_low'] = round(grouped['mean'] - grouped['std_dev'], 1)
    grouped['mean'] = round(grouped['mean'], 1)

    grouped['points'] = grouped.apply(calculate_points, axis=1)
    sorted_grouped = grouped.sort_values(by=['points', 'normal_low', 'normal_high', 'mean', 'count'], ascending=False)
    return sorted_grouped

In [35]:
subj = 'MathBlockBall100'
df = data_2024(file_path, AreaName, TerName, EOName, subj)
main(df)

     Statistic   Value
0         mean  118.87
1  normal_high  166.57
2   normal_low   71.17
3          max  200.00
4          min    0.00
5       median  134.00
6         q_25  108.00
7         q_75  147.00
                                                                                                                              EOName  count   mean    std_dev    max    min  normal_high  normal_low      points
4320                     Львівський фізико-математичний ліцей-інтернат при Львівському національному університеті імені Івана Франка    148  183.4  15.280636  200.0  123.0        198.7       168.1  251.021812
6156                   Політехнічний ліцей Національного технічного університету України "Київський політехнічний інститут" м. Києва     97  181.7  15.449883  200.0  145.0        197.1       166.2  247.604082
6509                                                                                Русанівський ліцей Дніпровського району м. Києва     29  182.6  13.873194  200.0  152.0        196.5       168.7  247.426667
7339  Технічний ліцей Національного технічного університету України "Київський політехнічний інститут" Солом'янського району м.Києва     87  180.9  15.286684  200.0  143.0        196.2       165.7  246.667045
2016                                                                    Дніпровський ліцей № 12 "Інтелект" Дніпровської міської ради     24  182.1  14.562957  200.0  149.0        196.6       167.5  244.550000
2986                                                                        Київський національний університет імені Тараса Шевченка     78  179.1  16.385690  200.0  131.0        195.4       162.7  241.990506
1649                                                                                     Гімназія №178 Солом'янського району м.Києва     31  180.4  19.198566  200.0  131.0        199.6       161.2  236.762500
2044                                                  Дніпровський науковий ліцей інформаційних технологій Дніпровської міської ради     93  175.2  16.373447  200.0  134.0        191.6       158.9  236.659574
8680                                                                                                             ліцей №142 м. Києва     66  177.9  19.801421  200.0  115.0        197.7       158.1  234.790299
8608                              комунальний заклад освіти "Дніпропетровський обласний ліцей-інтернат фізико-математичного профілю"     23  176.0  16.349808  200.0  147.0        192.3       159.6  232.750000
7891                                          Чернівецький ліцей №1 математичного та економічного профілів Чернівецької міської ради     58  174.4  17.530865  200.0  140.0        191.9       156.9  232.690678
8644                                                                                                                ліцей "Інтелект"     66  173.4  16.726429  200.0  134.0        190.1       156.6  232.562687
6265                                                                      Природничо-науковий ліцей №145 Печерського району м. Києва     50  174.9  18.345483  200.0  131.0        193.2       156.5  231.681373
4301                                                                                                      Львівська гімназія "Євшан"     57  172.2  16.676319  200.0  137.0        188.8       155.5  230.568966
7337                                                                                   Технічний ліцей Дніпровського району м. Києва    100  172.0  17.802153  200.0  131.0        189.8       154.1  229.624257

In [36]:
subj = 'PhysBlockBall100'
df = data_2024(file_path, AreaName, TerName, EOName, subj)
main(df)

     Statistic   Value
0         mean  121.56
1  normal_high  170.14
2   normal_low   72.98
3          max  200.00
4          min    0.00
5       median  131.00
6         q_25  109.00
7         q_75  148.00
                                                                                                                              EOName  count   mean    std_dev    max    min  normal_high  normal_low      points
2340  Технічний ліцей Національного технічного університету України "Київський політехнічний інститут" Солом'янського району м.Києва     20  184.4  12.214745  200.0  160.0        196.6       172.2  250.100000
1391                     Львівський фізико-математичний ліцей-інтернат при Львівському національному університеті імені Івана Франка     34  184.3  15.528509  200.0  131.0        199.9       168.8  248.377143
989                                                                         Київський національний університет імені Тараса Шевченка     25  175.2  14.563081  194.0  148.0        189.8       160.6  234.723077
1670                                           Надвірнянський ліцей "Престиж" Надвірнянської міської ради Івано-Франківської області     10  178.0  12.771496  200.0  156.0        190.8       165.2  232.781818
2014                                                                      Природничо-науковий ліцей №145 Печерського району м. Києва     13  178.5  15.903959  200.0  147.0        194.4       162.6  232.285714
700                                                   Долинський ліцей "Інтелект" Долинської міської ради Івано-Франківської області      3  192.7   8.082904  200.0  184.0        200.7       184.6  230.750000
2785                                                                                                             ліцей №142 м. Києва     15  175.5  17.179168  200.0  151.0        192.6       158.3  227.556250
2519                                                                             Чернігівський ліцей № 12 Чернігівської міської ради     17  174.0  18.963781  194.0  118.0        193.0       155.0  223.888889
2754                                           комунальний заклад загальної середньої освіти «Луцький ліцей №9 Луцької міської ради»      4  180.8   9.945686  189.0  169.0        190.7       170.8  222.040000
893                                                                   КОМУНАЛЬНИЙ ЗАКЛАД "ВІННИЦЬКИЙ ФІЗИКО-МАТЕМАТИЧНИЙ ЛІЦЕЙ № 17"     10  172.3  16.799802  189.0  134.0        189.1       155.5  219.113636
48                                                                                 Авіакосмічний ліцей ім. І.Сікорського НАУ м.Києва      9  172.2  16.483156  200.0  143.0        188.7       155.7  217.980000
2613                                                                                                             гімназія "Академія"      3  187.3  13.576941  200.0  173.0        200.9       173.8  217.250000
2076                                                                                Русанівський ліцей Дніпровського району м. Києва      9  170.8  15.690585  194.0  151.0        186.5       155.1  217.140000
676                                                   Дніпровський науковий ліцей інформаційних технологій Дніпровської міської ради     24  167.6  18.982400  200.0  137.0        186.6       148.6  216.956000
1237                                                                            Комунальний ліцей "Маріупольський ліцей міста Києва"      3  183.7  10.503968  194.0  173.0        194.2       173.2  216.500000

In [37]:
subj = 'ChemBlockBall100'
df = data_2024(file_path, AreaName, TerName, EOName, subj)
main(df)

     Statistic   Value
0         mean  128.74
1  normal_high  171.38
2   normal_low   86.09
3          max  200.00
4          min    0.00
5       median  138.00
6         q_25  116.00
7         q_75  150.00
                                                                                                             EOName  count   mean    std_dev    max    min  normal_high  normal_low      points
805     Львівський фізико-математичний ліцей-інтернат при Львівському національному університеті імені Івана Франка     17  181.6  15.227684  200.0  146.0        196.8       166.4  240.355556
833                                               Ліцей імені Олександра Цинкаловського Володимирської міської ради      4  189.5   8.020806  195.0  178.0        197.5       181.5  235.950000
378                                                                    Дубровицький ліцей Дубровицької міської ради      4  181.5   6.608076  186.0  172.0        188.1       174.9  227.370000
1620                   комунальний заклад освіти "Науковий медичний ліцей "Дніпро" Дніпропетровської обласної ради"      3  190.7   9.018500  200.0  182.0        199.7       181.6  227.000000
796                                                                                      Львівська гімназія "Євшан"      3  182.0   4.000000  186.0  178.0        186.0       178.0  222.500000
1611                          комунальний заклад загальної середньої освіти «Луцький ліцей №9 Луцької міської ради»      3  185.0  13.228757  195.0  170.0        198.2       171.8  214.750000
172                                                              Волинський науковий ліцей Волинської обласної ради     11  157.5   8.250620  170.0  140.0        165.7       149.2  211.366667
1483                                                            Чернігівський ліцей № 15 Чернігівської міської ради     11  160.0  11.924764  182.0  143.0        171.9       148.1  209.808333
1000                                                         Нововолинський науковий ліцей Волинської обласної ради     15  161.0  16.080156  195.0  135.0        177.1       144.9  208.293750
795                            Львівська академічна гімназія при Національному університеті "Львівська політехніка"      3  182.7  17.009801  200.0  166.0        199.7       165.7  207.125000
1070                                                    Обласний науковий ліцей в м.Рівне Рівненської обласної ради      7  163.0  13.662601  175.0  140.0        176.7       149.3  205.287500
893                                                         Ліцей №2 Шепетівської міської ради Хмельницької області      8  154.6   7.269064  168.0  144.0        161.9       147.4  204.722222
1156  Політехнічний ліцей Національного технічного університету України "Київський політехнічний інститут" м. Києва      6  162.8  14.062954  178.0  143.0        176.9       148.8  201.942857
347                                                               Дніпровський ліцей №137 Дніпровської міської ради      2  180.5   7.778175  186.0  175.0        188.3       172.7  201.483333
831                                                           Ліцей ім. Івана Пулюя Івано-Франківської міської ради      5  166.6  16.334014  195.0  156.0        182.9       150.3  200.400000

In [31]:
subj = 'BioBlockBall100'
df = data_2024(file_path, AreaName, TerName, EOName, subj)
main(df)

     Statistic   Value
0         mean  145.06
1  normal_high  163.03
2   normal_low  127.08
3          max  200.00
4          min    0.00
                                                                                                                                EOName  count   mean    std_dev    max    min  normal_high  normal_low      points
2318                                          Калуський ліцей імені Дмитра Бахматюка Калуської міської ради Івано-Франківської області      6  188.5   9.914636  196.0  170.0        198.4       178.6  242.385714
2258                                                                                 КОМУНАЛЬНИЙ ЗАКЛАД "РІШЕЛЬЄВСЬКИЙ НАУКОВИЙ ЛІЦЕЙ"      7  182.9   8.952254  200.0  170.0        191.8       173.9  239.112500
3813                                                                                         Ліцей №11 Івано-Франківської міської ради      4  188.5   4.725816  192.0  182.0        193.2       183.8  238.940000
4208                                                                Мукачівський ліцей Мукачівської міської ради Закарпатської області      5  186.4   7.635444  196.0  177.0        194.0       178.8  238.400000
7110                                            комунальний заклад загальної середньої освіти «Луцький ліцей №18 Луцької міської ради»      6  180.3   7.763161  192.0  172.0        188.1       172.6  234.242857
6073    Технічний ліцей Національного технічного університету України "Київський політехнічний інститут" Солом'янського району м.Києва      3  189.3   2.309401  192.0  188.0        191.6       187.0  233.750000
5794                                                           Спеціалізована школа №115 імені І.Огієнка Солом'янського району м.Києва      2  200.0   0.000000  200.0  200.0        200.0       200.0  233.333333
4278                                             Надвірнянський ліцей "Престиж" Надвірнянської міської ради Івано-Франківської області      4  188.2   9.032349  196.0  179.0        197.3       179.2  232.960000
5996  ТУЗЛІВСЬКИЙ ОПОРНИЙ ЗАКЛАД ЗАГАЛЬНОЇ СЕРЕДНЬОЇ ОСВІТИ ТУЗЛІВСЬКОЇ СІЛЬСЬКОЇ РАДИ БІЛГОРОД-ДНІСТРОВСЬКОГО РАЙОНУ ОДЕСЬКОЇ ОБЛАСТІ      3  190.7   4.618802  196.0  188.0        195.3       186.0  232.500000
3220                  Косівський ліцей №1 імені Ярослава Мудрого Косівської міської ради Косівського району Івано-Франківської області      7  178.6  10.783585  188.0  156.0        189.4       167.8  230.725000
7144                                      комунальний заклад освіти "Науковий медичний ліцей "Дніпро" Дніпропетровської обласної ради"     23  170.9  12.895751  192.0  138.0        183.8       158.0  230.416667
4252                                           Навчально-виховний комплекс "Інженерно-економічна школа - Львівський економічний ліцей"      3  186.0   1.732051  188.0  185.0        187.7       184.3  230.375000
7158                                                                                                                  ліцей "Інтелект"      7  180.6  13.587459  200.0  164.0        194.2       167.0  229.625000
3558                                              Львівська академічна гімназія при Національному університеті "Львівська політехніка"      5  184.6  13.183323  196.0  164.0        197.8       171.4  228.533333
6997                                                               комунальний заклад "Харківський ліцей №82 Харківської міської ради"      4  185.5   9.949874  196.0  177.0        195.4       175.6  228.280000

In [38]:
df = pd.concat(
    [
        data_2024(file_path, AreaName, TerName, EOName, 'MathBlockBall100'),
        data_2024(file_path, AreaName, TerName, EOName, 'PhysBlockBall100'),
        data_2024(file_path, AreaName, TerName, EOName, 'ChemBlockBall100'),
        data_2024(file_path, AreaName, TerName, EOName, 'BioBlockBall100'),
    ],
    ignore_index=True,
)

main(df)

     Statistic   Value
0         mean  122.90
1  normal_high  168.39
2   normal_low   77.41
3          max  200.00
4          min    0.00
5       median  134.00
6         q_25  115.00
7         q_75  148.00
                                                                                                                              EOName  count   mean    std_dev    max    min  normal_high  normal_low      points
4320                     Львівський фізико-математичний ліцей-інтернат при Львівському національному університеті імені Івана Франка    204  183.3  15.263520  200.0  123.0        198.6       168.0  251.180488
7339  Технічний ліцей Національного технічного університету України "Київський політехнічний інститут" Солом'янського району м.Києва    110  181.8  14.624223  200.0  143.0        196.4       167.2  249.293694
6156                   Політехнічний ліцей Національного технічного університету України "Київський політехнічний інститут" м. Києва    112  179.7  16.252264  200.0  143.0        195.9       163.4  243.653982
2986                                                                        Київський національний університет імені Тараса Шевченка    106  178.3  15.874610  200.0  131.0        194.2       162.4  242.082243
6509                                                                                Русанівський ліцей Дніпровського району м. Києва     39  179.0  15.543635  200.0  150.0        194.6       163.5  241.162500
2016                                                                    Дніпровський ліцей № 12 "Інтелект" Дніпровської міської ради     31  179.3  15.444455  200.0  145.0        194.7       163.8  240.581250
1649                                                                                     Гімназія №178 Солом'янського району м.Києва     34  180.9  18.914693  200.0  131.0        199.8       161.9  238.224286
8680                                                                                                             ліцей №142 м. Києва     85  177.1  19.053316  200.0  115.0        196.1       158.0  235.162791
8644                                                                                                                ліцей "Інтелект"     74  174.2  16.453563  200.0  134.0        190.7       157.8  234.596000
2044                                                  Дніпровський науковий ліцей інформаційних технологій Дніпровської міської ради    118  173.7  17.067539  200.0  134.0        190.8       156.6  233.584034
4301                                                                                                      Львівська гімназія "Євшан"     64  173.3  16.322389  200.0  137.0        189.6       156.9  232.936154
6265                                                                      Природничо-науковий ліцей №145 Печерського району м. Києва     68  174.6  18.360662  200.0  131.0        192.9       156.2  232.036232
5087                                         Навчально-виховний комплекс "Інженерно-економічна школа - Львівський економічний ліцей"     27  172.6  14.716117  200.0  145.0        187.3       157.8  231.064286
7891                                          Чернівецький ліцей №1 математичного та економічного профілів Чернівецької міської ради     68  172.8  18.138720  200.0  131.0        191.0       154.7  229.807971
8608                              комунальний заклад освіти "Дніпропетровський обласний ліцей-інтернат фізико-математичного профілю"     29  173.5  17.837802  200.0  145.0        191.4       155.7  228.360000